### ISSUE TITLE
empty array on v1/order/orders

### ISSUE THREAD

**Issue by robertconstantin** [huobiapi/REST-Node.js-demo#1]
I have tried to get the orders from my account using get_open_orders method, I also added all the states from the api docs and I still get empty array. I have used the symbols that I have traded, so what could be the problem?

**Comment by FredYuuu** [comment]
Try to add the states(submitted, partial-filled, partial-canceled, filled, canceled) seperated by ',' that work for me :)

**Comment by robertciudica** [comment]
@FredYuuu 
```javascript
get_open_orders: function(symbol) {
        var path = `/v1/order/orders`;
        var body = get_body();
        body.symbol = symbol;
        body.states = `submitted,partial-filled,partial-canceled,filled,canceled`;
        var payload = sign_sha('GET', URL_HUOBI_PRO, path, body);
        return call_api('GET', path, payload, body);
    }
```
this is how it looks and all I get, no matter what symbol I add is:
`{ status: 'ok', data: [] } `

Do you have any others ideas?

**Comment by robertciudica** [comment]
I figured up in the meantime, I had older orders so they didn't show up. I have added start-date and it works now. 
Thanks anyway @FredYuuu
